name: publish extensions
on:
  release:
    types: [created]

jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: compare git commit id
        run: |
          git checkout main
          if [ $GITHUB_SHA == $(git log -n 1 --pretty=format:"%H") ]
          then
            echo "release tag's HEAD equals main branch"
          else
            echo "release tag's HEAD NOT equals main branch (publish only main  branch)"
            exit 1
          fi
          git checkout -
  test:
    runs-on: ubuntu-latest
    needs:
      - branch-check
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install -g @vscode/vsce
          npm install
      - name: format check
        run: npm run fmt:check
      - name: Publish extension
        id: publisher
        uses: sigma/vsce-publish-action@v0.0.2
        with:
          vsce_token: ${{ secrets.VSCE_TOKEN }}
          build_pkg: yes